"""Generate realistic daily energy readings seed data.

One generation reading and one consumption reading per meter per day.
Generation follows a solar seasonal curve (peaks late June, minimal in
December) with day-to-day weather variation. Consumption peaks in winter
and dips at weekends.

Five non-consecutive days in February 2026 have no generation at all --
an overcast spell.
"""

import math
import random
from datetime import date, timedelta

random.seed(20260818)

# meter_id, capacity scale factor
METERS = [
    ("LGY-19A-12345678", 1.00),
    ("LGY-21B-23456789", 0.82),
    ("EDM-1840-123456", 1.15),
    ("EDM-1840-234567", 0.74),
    ("KAM-30C-0123456", 0.95),
    ("ITR-CF-12345678", 1.30),
    ("ITR-CF-23456789", 0.68),
]

START = date(2025, 1, 1)
END = date(2026, 8, 18)

OVERCAST_DAYS = {
    date(2026, 2, 3),
    date(2026, 2, 7),
    date(2026, 2, 12),
    date(2026, 2, 18),
    date(2026, 2, 24),
}

GEN_PEAK_KWH = 420.0
CON_PEAK_KWH = 340.0


def solar_seasonal(d: date) -> float:
    """0.15 in midwinter, 1.0 at the summer solstice."""
    doy = d.timetuple().tm_yday
    curve = 0.5 + 0.5 * math.cos(2 * math.pi * (doy - 172) / 365.25)
    return 0.15 + 0.85 * curve


def demand_seasonal(d: date) -> float:
    """1.0 in midwinter, 0.55 in midsummer."""
    doy = d.timetuple().tm_yday
    curve = 0.5 + 0.5 * math.cos(2 * math.pi * (doy - 15) / 365.25)
    return 0.55 + 0.45 * curve


def generation_kwh(d: date, scale: float) -> float:
    weather = random.uniform(0.1, 0.4) if random.random() < 0.12 else random.uniform(0.4, 1.0)
    return round(GEN_PEAK_KWH * scale * solar_seasonal(d) * weather, 2)


def consumption_kwh(d: date, scale: float) -> float:
    weekend = 0.75 if d.weekday() >= 5 else 1.0
    noise = random.uniform(0.85, 1.15)
    return round(CON_PEAK_KWH * scale * demand_seasonal(d) * weekend * noise, 2)


def rows():
    day = START
    while day <= END:
        for meter_id, scale in METERS:
            if day not in OVERCAST_DAYS:
                yield (meter_id, f"{day.isoformat()}T12:00:00+00:00",
                       generation_kwh(day, scale), "generation")
            yield (meter_id, f"{day.isoformat()}T19:00:00+00:00",
                   consumption_kwh(day, scale), "consumption")
        day += timedelta(days=1)


def main():
    all_rows = list(rows())
    batches = [all_rows[i:i + 500] for i in range(0, len(all_rows), 500)]

    lines = [
        "-- Seed data for energy_readings",
        "-- Generated by generate_db_seed.py -- do not edit by hand.",
        f"-- {START.isoformat()} to {END.isoformat()}, {len(METERS)} meters, {len(all_rows)} readings.",
        "-- Five days in February 2026 have no generation (overcast spell).",
        "",
    ]

    for batch in batches:
        lines.append(
            'INSERT INTO public.energy_readings (meter_id, "timestamp", kwh, reading_type)\nVALUES'
        )
        values = [
            f"    ('{m}', '{ts}', {kwh}, '{rt}')"
            for m, ts, kwh, rt in batch
        ]
        lines.append(",\n".join(values) + ";")
        lines.append("")

    with open("../init/02_add_data.sql", "w") as f:
        f.write("\n".join(lines))

    print(f"{len(all_rows)} rows across {len(batches)} statements")


if __name__ == "__main__":
    main()